name: Run csv_json_converter

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run csv_json_converter script
      run: python csv_json_converter.py

    - name: Commit generated json
      run: |
            git config --global user.name 'dyzancorn'
            git config --global user.email '175410061+dyzancorn@users.noreply.github.com'
            git add simsRadioData.json
            git commit -am "Update simsRadioData"
            git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

